# Ejercicios capítulo 1.

Ejercicios prácticos de programación en Python enfocados en conceptos básicos como son:

  - Declaración y asignación de variables
  - Tipos y estructuras de datos
  - Operaciones artiméticas
  - Operadores de comparación
  - La función Print
  - Arrays en NumPy

**Ejercicio 1: Declaración de Variables y Tipos de Datos**

Crea cuatro variables con los siguientes nombres y valores:
* `nombre`: Asígna un valor de texto.
* `edad`: Asígna un valor numérico entero.
* `estatura`: Asígna un valor decimal.
* `es_estudiante`: Asígna un valor booleano.

Finalmente, utiliza la función `type()` para imprimir el tipo de dato de cada una de estas variables.


In [ ]:
nombre = "Ana"
edad = 25
estatura = 1.68
es_estudiante = True

print(type(nombre))
print(type(edad))
print(type(estatura))
print(type(es_estudiante))


<class 'str'>
<class 'int'>
<class 'float'>
<class 'bool'>


**Ejercicio 2: Operaciones Aritméticas Básicas**

1.  Crea dos variables llamadas `numero1` y `numero2` y asígnales dos números enteros de tu elección.
2.  Muestra en pantalla el resultado de las siguientes operaciones aritméticas entre ellas:
    * Suma (`+`)
    * Resta (`-`)
    * Multiplicación (`*`)
    * División (`/`)
    * División entera (`//`)
    * Módulo (`%`)

Asegúrate de que cada resultado se imprima con un texto descriptivo.

In [ ]:
numero1 = 10
numero2 = 3

print(f"Operaciones con los números {numero1} y {numero2}:\n")

print(f"Suma: {numero1 + numero2}")
print(f"Resta: {numero1 - numero2}")
print(f"Multiplicación: {numero1 * numero2}")
print(f"División: {numero1 / numero2}")
print(f"División entera: {numero1 // numero2}")
print(f"Módulo (Resto): {numero1 % numero2}")

La suma es: 10


# Ejercicio 3: Operadores de Comparación

  1. Crea dos variables llamadas valor1 y valor2 y asígnales dos números de tu elección.

  2. Muestra en pantalla el resultado (True o False) de realizar las siguientes comparaciones entre las variables:

    * Mayor que (>)
    * Menor que (<)
    * Igual a (==)
    * Diferente de (!=)
    * Mayor o igual que (>=)
    * Menor o igual que (<=)

Asegúrate de que cada resultado se imprima junto con un texto descriptivo que aclare qué comparación se está realizando.


In [1]:
valor1 = 15
valor2 = 10

print(f"Resultados de comparar {valor1} y {valor2}:\n")

print(f"¿Es {valor1} mayor que {valor2}?: {valor1 > valor2}")
print(f"¿Es {valor1} menor que {valor2}?: {valor1 < valor2}")
print(f"¿Es {valor1} igual a {valor2}?: {valor1 == valor2}")
print(f"¿Es {valor1} diferente de {valor2}?: {valor1 != valor2}")
print(f"¿Es {valor1} mayor o igual que {valor2}?: {valor1 >= valor2}")
print(f"¿Es {valor1} menor o igual que {valor2}?: {valor1 <= valor2}")

Resultados de comparar 15 y 10:

¿Es 15 mayor que 10?: True
¿Es 15 menor que 10?: False
¿Es 15 igual a 10?: False
¿Es 15 diferente de 10?: True
¿Es 15 mayor o igual que 10?: True
¿Es 15 menor o igual que 10?: False


### **Ejercicio 4: Operaciones Fundamentales con Listas**

**Instrucciones:**

1.  **Creación y Corrección de la Lista**:
    * Crea una lista llamada `frutas`. Asegúrate de que cada fruta sea un elemento `string` individual. La lista debe contener: "manzana", "banana", "cereza" y "durazno".
    * Imprime la lista original para verificar su contenido.

2.  **Acceder a Elementos**:
    * Imprime el primer elemento de la lista
    * Imprime el último elemento de la lista

3.  **Modificar un Elemento**:
    * Las listas son *mutables*. Cambia el segundo elemento (índice `1`) de "banana" a "mango".
    * Vuelve a imprimir la lista completa para ver el cambio reflejado.

4.  **Agregar Elementos**:
    * Usa el método `.append()` para agregar una nueva fruta (por ejemplo, "kiwi") al **final** de la lista.
    * Usa el método `.insert()` para agregar otra fruta (por ejemplo, "uva") en una posición específica, como el índice `2`.
    * Imprime la lista después de cada adición para observar los cambios.

5.  **Eliminar Elementos**:
    * Usa el método `.remove()` para eliminar una fruta de la lista por su nombre (por ejemplo, "cereza").
    * Usa el método `.pop()` para eliminar el último elemento de la lista. Almacena el elemento eliminado en una variable y muéstralo en pantalla.
    * Imprime la lista después de cada eliminación.

6.  **Longitud y Búsqueda**:
    * Utiliza la función `len()` para obtener e imprimir el número total de elementos que quedan en tu lista.

In [5]:
frutas = ["manzana", "banana", "cereza", "durazno"]
print(f"1. Lista original: {frutas}\n")

print("2. Accediendo a los elementos:")
print(f"   - El primer elemento es: {frutas[0]}")
print(f"   - El último elemento es: {frutas[-1]}\n")

print("3. Modificando el segundo elemento:")
frutas[1] = "mango"
print(f"   - Lista modificada: {frutas}\n")

print("4. Agregando nuevos elementos:")
frutas.append("kiwi")
print(f"   - Lista después de usar append('kiwi'): {frutas}")
frutas.insert(2, "uva")
print(f"   - Lista después de usar insert(2, 'uva'): {frutas}\n")

print("5. Eliminando elementos:")
frutas.remove("cereza")
print(f"   - Lista después de remover 'cereza': {frutas}")
fruta_eliminada = frutas.pop()
print(f"   - Lista después de usar pop(): {frutas}")
print(f"   - La fruta eliminada fue: '{fruta_eliminada}'\n")

print("6. Longitud y búsqueda en la lista final:")
total_frutas = len(frutas)
print(f"   - El número final de frutas en la lista es: {total_frutas}")

1. Lista original: ['manzana', 'banana', 'cereza', 'durazno']

2. Accediendo a los elementos:
   - El primer elemento es: manzana
   - El último elemento es: durazno

3. Modificando el segundo elemento:
   - Lista modificada: ['manzana', 'mango', 'cereza', 'durazno']

4. Agregando nuevos elementos:
   - Lista después de usar append('kiwi'): ['manzana', 'mango', 'cereza', 'durazno', 'kiwi']
   - Lista después de usar insert(2, 'uva'): ['manzana', 'mango', 'uva', 'cereza', 'durazno', 'kiwi']

5. Eliminando elementos:
   - Lista después de remover 'cereza': ['manzana', 'mango', 'uva', 'durazno', 'kiwi']
   - Lista después de usar pop(): ['manzana', 'mango', 'uva', 'durazno']
   - La fruta eliminada fue: 'kiwi'

6. Longitud y búsqueda en la lista final:
   - El número final de frutas en la lista es: 4


### **Ejercicio 5: Dominando el Rebanado de Listas (Slicing)**

**Instrucciones:**

1.  **Lista de Referencia**:
    * Crea una lista llamada `numeros` que contenga los siguientes enteros: `10, 20, 30, 40, 50, 60, 70, 80, 90, 100`.
    * Imprime la lista completa para tenerla como referencia.

2.  **Slicing Básico**:
    * Obtén y muestra los **tres primeros elementos** de la lista.
    * Obtén y muestra los elementos **desde el tercer elemento hasta el final** de la lista (incluyendo el tercero).

3.  **Slicing con Inicio y Fin**:
    * Crea un slicing que contenga los elementos desde el índice `2` hasta el índice `5` (sin incluir este último).
    * Muestra el resultado en pantalla con un texto descriptivo.

4.  **Slicing con Índices Negativos**:
    * Utiliza índices negativos para obtener los **últimos cuatro elementos** de la lista.
    * Crea un slicing que excluya el primer y el último elemento de la lista.

5.  **Slicing con Pasos (Steps)**:
    * Obtén todos los elementos de la lista, pero **de dos en dos** (es decir, uno sí, uno no).
    * Crea una rebanada que invierta completamente el orden de la lista.
    * Muestra ambos resultados.

In [8]:
numeros = [10, 20, 30, 40, 50, 60, 70, 80, 90, 100]
print(f"1. Lista original: {numeros}\n")

print("2. Slicing Básico:")
primeros_tres = numeros[:3]
print(f"   - Los tres primeros elementos son: {primeros_tres}")
desde_el_tercero = numeros[2:]
print(f"   - Desde el tercer elemento hasta el final: {desde_el_tercero}\n")

print("3. Slicing con inicio y fin definidos:")
segmento = numeros[2:5]
print(f"   - Elementos del índice 2 al 5 (sin incluir el 5): {segmento}\n")

print("4. Slicing con índices negativos:")
ultimos_cuatro = numeros[-4:]
print(f"   - Los últimos cuatro elementos: {ultimos_cuatro}")
sin_extremos = numeros[1:-1]
print(f"   - Lista sin el primer y último elemento: {sin_extremos}\n")

print("5. Slicing con pasos:")
de_dos_en_dos = numeros[::2]
print(f"   - Elementos de dos en dos: {de_dos_en_dos}")
lista_invertida = numeros[::-1]
print(f"   - La lista completamente invertida es: {lista_invertida}")

1. Lista original: [10, 20, 30, 40, 50, 60, 70, 80, 90, 100]

2. Slicing Básico:
   - Los tres primeros elementos son: [10, 20, 30]
   - Desde el tercer elemento hasta el final: [30, 40, 50, 60, 70, 80, 90, 100]

3. Slicing con inicio y fin definidos:
   - Elementos del índice 2 al 5 (sin incluir el 5): [30, 40, 50]

4. Slicing con índices negativos:
   - Los últimos cuatro elementos: [70, 80, 90, 100]
   - Lista sin el primer y último elemento: [20, 30, 40, 50, 60, 70, 80, 90]

5. Slicing con pasos:
   - Elementos de dos en dos: [10, 30, 50, 70, 90]
   - La lista completamente invertida es: [100, 90, 80, 70, 60, 50, 40, 30, 20, 10]


### **Ejercicio 6: Creación de Arrays Fundamentales en NumPy**

**Instrucciones:**


1.  Crea un vector (array de 1D) llamado `vector_arange` que comience en 5, termine antes de 15, y avance en pasos de 0.75.

3.  Crea un vector llamado `vector_linspace` que contenga exactamente 10 puntos, distribuidos uniformemente entre 0 y 20 (incluyendo ambos extremos).

4.  Crea una matriz (array de 2D) de 3 filas y 4 columnas llamada `matriz_ceros`, donde todos sus elementos sean ceros.

5.  Crea una matriz de 2 filas y 5 columnas llamada `matriz_unos`, donde todos sus elementos sean unos y el tipo de dato sea entero (`int`).

6.  Genera y muestra una matriz identidad de 4x4 llamada `matriz_identidad`.

Asegúrate de imprimir cada uno de los arrays creados con un texto descriptivo que aclare qué función se utilizó.

In [10]:
import numpy as np

print("1. Creando un vector con np.arange(5, 15, 0.75):")
vector_arange = np.arange(5, 15, 0.75)
print(vector_arange)
print("-" * 30)

print("2. Creando un vector con 10 puntos entre 0 y 20 con np.linspace():")
vector_linspace = np.linspace(0, 20, 10)
print(vector_linspace)
print("-" * 30)

print("3. Creando una matriz de ceros de 3x4 con np.zeros():")
matriz_ceros = np.zeros((3, 4))
print(matriz_ceros)
print("-" * 30)

print("4. Creando una matriz de unos enteros de 2x5 con np.ones():")
matriz_unos = np.ones((2, 5), dtype=int)
print(matriz_unos)
print("-" * 30)

print("5. Creando una matriz identidad de 4x4 con np.eye():")
matriz_identidad = np.eye(4)
print(matriz_identidad)

1. Creando un vector con np.arange(5, 15, 0.75):
[ 5.    5.75  6.5   7.25  8.    8.75  9.5  10.25 11.   11.75 12.5  13.25
 14.   14.75]
------------------------------
2. Creando un vector con 10 puntos entre 0 y 20 con np.linspace():
[ 0.          2.22222222  4.44444444  6.66666667  8.88888889 11.11111111
 13.33333333 15.55555556 17.77777778 20.        ]
------------------------------
3. Creando una matriz de ceros de 3x4 con np.zeros():
[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
------------------------------
4. Creando una matriz de unos enteros de 2x5 con np.ones():
[[1 1 1 1 1]
 [1 1 1 1 1]]
------------------------------
5. Creando una matriz identidad de 4x4 con np.eye():
[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


### **Ejercicio 7: Formateo Avanzado de Cadenas con F-Strings**

**Instrucciones:**

1.  Define las siguientes variables que usaremos a lo largo del ejercicio:
        * `nombre = "Isabel"`
        * `profesion = "Científica de Datos"`
        * `edad = 34`
        * `salario_anual = 1250450.875`
        * `tasa_impuesto = 0.215`

2.  Muestra una presentación básica, pero esta vez, calcula e imprime la **edad de Isabel en 5 años** directamente dentro de la f-string. En la misma línea, muestra su profesión en **mayúsculas** llamando al método `.upper()` dentro de la f-string.

3.  El `salario_anual` tiene demasiados decimales para un reporte financiero. Muéstralo formateado para que tenga solo **dos decimales**. La `tasa_impuesto` es un número flotante. Muéstrala como un **porcentaje** con un solo decimal. (Pista: `:.1%`)

4.  Imagina que estás creando una tabla. Muestra el nombre y la profesión en dos líneas, asegurándote de que cada campo ocupe un **espacio mínimo de 25 caracteres**, alineado a la izquierda. Muestra el `salario_anual` formateado con un **separador de comas** para los miles y con dos decimales, para facilitar su lectura.


In [11]:
nombre = "Isabel"
profesion = "Científica de Datos"
edad = 34
salario_anual = 1250450.875
tasa_impuesto = 0.215

print("Uso de expresiones y métodos:")
print(f"Hola, soy {nombre}. En 5 años tendré {edad + 5} años.")
print(f"Mi profesión es: {profesion.upper()}.\n")

print("Formateo de números flotantes:")
# :.2f -> Flotante con 2 decimales
print(f"Salario anual (formateado): ${salario_anual:.2f}")
# :.1% -> Formato de porcentaje con 1 decimal
print(f"Tasa de impuesto: {tasa_impuesto:.1%}\n")

print("Alineación y formato de números grandes:")
# :<25 -> Alineado a la izquierda, 25 caracteres de ancho
print(f"{'Nombre:':<10} {nombre:<25}")
print(f"{'Profesión:':<10} {profesion:<25}")
# :,.2f -> Coma como separador de miles, flotante con 2 decimales
print(f"{'Salario:':<10} ${salario_anual:,.2f}\n")

Uso de expresiones y métodos:
Hola, soy Isabel. En 5 años tendré 39 años.
Mi profesión es: CIENTÍFICA DE DATOS.

Formateo de números flotantes:
Salario anual (formateado): $1250450.88
Tasa de impuesto: 21.5%

Alineación y formato de números grandes:
Nombre:    Isabel                   
Profesión: Científica de Datos      
Salario:   $1,250,450.88



### **Ejercicio 8: Trabajando con Tuplas y su Inmutabilidad**

**Instrucciones:**

1.  Crea una tupla llamada `ubicacion_zocalo` que contenga tres elementos: la latitud (19.4326), la longitud (-99.1332) y la altitud en metros (2240).
    * Imprime la tupla completa.
    * Accede e imprime cada elemento de la tupla utilizando su índice, junto con un texto descriptivo ("Latitud:", "Longitud:", "Altitud:").

2.  Asigna los valores de `ubicacion_zocalo` a tres variables nuevas (`latitud`, `longitud`, `altitud`) en una sola línea de código.
    * Imprime cada una de estas nuevas variables.

3.  Intenta modificar el primer elemento (la latitud) de la tupla `ubicacion_zocalo` para asignarle un nuevo valor (por ejemplo, `19.5`).
    * **Observación Importante**: Este código **generará un error** (`TypeError`).

4.  Crea una lista llamada `puntos_cdmx` que contenga tres tuplas. Cada tupla representará un punto de interés con su nombre y coordenadas:
        * ("Ángel de la Independencia", (19.4270, -99.1677))
        * ("Palacio de Bellas Artes", (19.4352, -99.1412))
        * ("Museo Nacional de Antropología", (19.4260, -99.1863))
   

In [15]:

ubicacion_zocalo = (19.4326, -99.1332, 2240)
print(f"La tupla creada es: {ubicacion_zocalo}")

# Acceder a cada elemento por su índice
print(f"Latitud: {ubicacion_zocalo[0]}")
print(f"Longitud: {ubicacion_zocalo[1]}")
print(f"Altitud: {ubicacion_zocalo[2]} metros\n")


# Desempaquetado de Tuplas
latitud, longitud, altitud = ubicacion_zocalo
print(f"Valor de la variable 'latitud': {latitud}")
print(f"Valor de la variable 'longitud': {longitud}")
print(f"Valor de la variable 'altitud': {altitud}\n")

print("Intentar modificar una tupla genera un TypeError.")
print("La siguiente línea de código está comentada porque, si se ejecuta, detendría el programa:")
#ubicacion_zocalo[0] = 19.5 # Descomentar esta linea para que se produzca el error


# Lista de Tuplas
puntos_cdmx = [
    ("Ángel de la Independencia", (19.4270, -99.1677)),
    ("Palacio de Bellas Artes", (19.4352, -99.1412)),
    ("Museo Nacional de Antropología", (19.4260, -99.1863))
]


La tupla creada es: (19.4326, -99.1332, 2240)
Latitud: 19.4326
Longitud: -99.1332
Altitud: 2240 metros

Valor de la variable 'latitud': 19.4326
Valor de la variable 'longitud': -99.1332
Valor de la variable 'altitud': 2240

Intentar modificar una tupla genera un TypeError.
La siguiente línea de código está comentada porque, si se ejecuta, detendría el programa:


### **Ejercicio 9: Definición y Acceso a un Diccionario**

**Instrucciones:**

1.  Crea un diccionario llamado `estudiante` que contenga la siguiente información:
    * `"nombre"`: "Laura"
    * `"edad"`: 22
    * `"carrera"`: "Economía"
    * `"semestre"`: 5

2.  Imprime el diccionario completo para verificar su creación.

In [16]:
estudiante = {
    "nombre": "Laura",
    "edad": 22,
    "carrera": "Economía",
    "semestre": 5
}

print(f"Diccionario creado: {estudiante}")

Diccionario creado: {'nombre': 'Laura', 'edad': 22, 'carrera': 'Economía', 'semestre': 5}


### **Ejercicio 10: Atributos y Operaciones Vectorizadas en NumPy**

**Instrucciones:**

1.  **Creación del Array**:
    * Utilizando `np.arange()`, crea un array llamado `datos_numericos` que contenga todos los números enteros del 10 al 25.
    * Imprime el array para verificar su contenido.

2.  **Inspección de Atributos**:
    *  Imprime los siguientes atributos de `datos_numericos`:
        * `.shape` (su forma)
        * `.size` (el número total de elementos)
        * `.ndim` (el número de dimensiones)

3.  **Operaciones Vectorizadas**:
    * Crea un nuevo array llamado `datos_transformados` que sea el resultado de multiplicar `datos_numericos` por 5 y luego sumarle 100 a cada elemento.
    * Imprime el nuevo array `datos_transformados`.

4.  **Filtro Booleano (Vectorizado)**:
    * Crea un array booleano llamado `mayores_a_20` que indique, con `True` o `False`, qué elementos del array original `datos_numericos` son mayores que 20.
    * Imprime este array booleano.

5.  **Slicing **:
    * Crea una sub-sección del array original llamada `segmento` que contenga los elementos desde el índice 5 hasta el 10 (sin incluir el 10).
    * Imprime `segmento`.

In [18]:
import numpy as np

# 1. Creación del Array
datos_numericos = np.arange(10, 26)
print(f"Array original: {datos_numericos}\n")

# 2. Inspección de Atributos
print("--- 2. Atributos del Array ---")
print(f"Forma (Shape): {datos_numericos.shape}")
print(f"Total de elementos (Size): {datos_numericos.size}")
print(f"Número de dimensiones (ndim): {datos_numericos.ndim}\n")

# 3. Operaciones Vectorizadas
print("--- 3. Operaciones Vectorizadas ---")
# La operación se aplica a cada elemento de forma simultánea.
datos_transformados = (datos_numericos * 5) + 100
print(f"Array transformado (x5 + 100): {datos_transformados}\n")

# 4. Filtro Booleano (Vectorizado)
print("--- 4. Filtro Booleano ---")
# La comparación se aplica a cada elemento, devolviendo un array de booleanos.
mayores_a_20 = datos_numericos > 20
print(f"¿Elementos mayores a 20?: {mayores_a_20}\n")

# 5. Slicing
print("--- 5. Slicing del Array ---")
# Se extraen los elementos desde el índice 5 hasta el 9 (el 10 no se incluye).
segmento = datos_numericos[5:10]
print(f"Segmento del array (índices 5 al 9): {segmento}")

Array original: [10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25]

--- 2. Atributos del Array ---
Forma (Shape): (16,)
Total de elementos (Size): 16
Número de dimensiones (ndim): 1

--- 3. Operaciones Vectorizadas ---
Array transformado (x5 + 100): [150 155 160 165 170 175 180 185 190 195 200 205 210 215 220 225]

--- 4. Filtro Booleano ---
¿Elementos mayores a 20?: [False False False False False False False False False False False  True
  True  True  True  True]

--- 5. Slicing del Array ---
Segmento del array (índices 5 al 9): [15 16 17 18 19]


### **Ejercicio 11: Indexación y Selección de Datos en NumPy**

**Instrucciones:**

1.  **Creación de un Array 2D (Matriz)**:
    * Para este ejercicio, crea una matriz de 3x4 (3 filas, 4 columnas) llamada `matriz_datos`.
    * Llénala con los números del 1 al 12. Una forma fácil de hacerlo es con `np.arange(1, 13).reshape(3, 4)`.
    * Imprime la matriz.

2.  **Indexación Básica en 2D**:
    * Accede y muestra el elemento que se encuentra en la segunda fila y tercera columna.
    * Accede y muestra la primera fila completa de la matriz.
    * Accede y muestra la segunda columna completa de la matriz.

3.  **Slicing en 2D**:
    * Crea y muestra una sub-matriz de 2x2 que contenga los elementos de las dos primeras filas y las dos últimas columnas.

4.  **Indexación**:
    * Primero, crea un array de 1D llamado `vector` con los números: `5, 10, 15, 20, 25, 30`.
    * Utiliza una lista de índices `[0, 2, 5]` para seleccionar y mostrar el primer, tercer y sexto elemento de `vector`.

5.  **Indexación con Máscara Booleana**:
    * Utilizando la `matriz_datos` del primer paso, crea una máscara booleana que identifique qué elementos son mayores a 8.
    * Usa esta máscara para seleccionar únicamente dichos elementos de la matriz original.
    * Imprime los valores seleccionados.

In [20]:
import numpy as np

# 1. Creación de un Array 2D (Matriz)
print("--- 1. Matriz de Datos ---")
matriz_datos = np.arange(1, 13).reshape(3, 4)
print(f"{matriz_datos}\n")


# 2. Indexación Básica en 2D
print("--- 2. Indexación Básica en 2D ---")
# Elemento en la fila 1 (la segunda), columna 2 (la tercera)
elemento = matriz_datos[1, 2]
print(f"Elemento en [1, 2]: {elemento}")

# Primera fila completa (índice 0)
primera_fila = matriz_datos[0] # o matriz_datos[0, :]
print(f"Primera fila completa: {primera_fila}")

# Segunda columna completa (índice 1)
segunda_columna = matriz_datos[:, 1]
print(f"Segunda columna completa: {segunda_columna}\n")


# 3. Slicing en 2D
print("--- 3. Slicing en 2D ---")
# Filas 0 a 1 (sin incluir la 2), columnas 2 a 3 (sin incluir la 4)
sub_matriz = matriz_datos[0:2, 2:4]
print(f"Sub-matriz de 2x2:\n{sub_matriz}\n")


# 4. Indexación
print("--- 4. Indexación 'Fancy' ---")
vector = np.array([5, 10, 15, 20, 25, 30])
indices = [0, 2, 5]
seleccion_fancy = vector[indices]
print(f"Vector original: {vector}")
print(f"Selección con índices {indices}: {seleccion_fancy}\n")


# 5. Indexación con Máscara Booleana
print("--- 5. Indexación con Máscara Booleana ---")
# La máscara es un array de True/False del mismo tamaño que la matriz
mascara = matriz_datos > 8
print(f"Máscara booleana (elementos > 8):\n{mascara}")

# Usar la máscara para seleccionar solo los elementos que son True
valores_filtrados = matriz_datos[mascara]
print(f"\nValores mayores a 8: {valores_filtrados}")

--- 1. Matriz de Datos ---
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]

--- 2. Indexación Básica en 2D ---
Elemento en [1, 2]: 7
Primera fila completa: [1 2 3 4]
Segunda columna completa: [ 2  6 10]

--- 3. Slicing en 2D ---
Sub-matriz de 2x2:
[[3 4]
 [7 8]]

--- 4. Indexación 'Fancy' ---
Vector original: [ 5 10 15 20 25 30]
Selección con índices [0, 2, 5]: [ 5 15 30]

--- 5. Indexación con Máscara Booleana ---
Máscara booleana (elementos > 8):
[[False False False False]
 [False False False False]
 [ True  True  True  True]]

Valores mayores a 8: [ 9 10 11 12]


### **Ejercicio 12: Indexación y Slicing**

**Instrucciones:**

1.  **Creación del Conjunto de Datos**:
    * Crea la matriz llamada `datos_sensor` con los números del 0 al 35 y dale la forma correcta usando `np.arange(36).reshape(6, 6)`.
    * Imprime la matriz.

2.  **Slicing con Pasos (Step)**:
    * Extrae una nueva matriz que contenga únicamente las **filas con índice par** (0, 2, 4) de la matriz original.
    * Imprime este nuevo sub-array.

3.  **Modificación de una Fila Completa**:
    * Selecciona la última fila de `datos_sensor` y **asigna a todos sus elementos el valor `99`**.
    * Imprime la matriz `datos_sensor` completa para verificar que la última fila ha sido modificada.

4.  **Modificación de una Columna Específica**:
    * Selecciona la primera columna (índice 0) de la matriz ya modificada y **asigna a todos sus elementos el valor `0`**.
    * Imprime la matriz `datos_sensor` de nuevo para ver este segundo cambio.

5.  **Extracción y Modificación de un Bloque Interno**:
    * Selecciona un bloque central de 2x2 de la matriz (filas 2 y 3, columnas 2 y 3).
    * Multiplica este bloque por 100 y reasígnalo a su misma posición en la matriz `datos_sensor`.
    * Imprime la matriz final para observar todos los cambios acumulados.

In [21]:
import numpy as np

# 1. Creación del Conjunto de Datos
print("--- 1. Matriz Original de Datos del Sensor ---")
datos_sensor = np.arange(36).reshape(6, 6)
print(f"{datos_sensor}\n")


# 2. Slicing con Pasos (Step)
print("--- 2. Selección de Filas Pares ---")
# [::2] significa empezar al principio, terminar al final, en pasos de 2
filas_pares = datos_sensor[::2, :]
print(f"{filas_pares}\n")


# 3. Modificación de una Fila Completa
print("--- 3. Modificando la Última Fila a 99 ---")
datos_sensor[-1, :] = 99
print(f"{datos_sensor}\n")


# 4. Modificación de una Columna Específica
print("--- 4. Modificando la Primera Columna a 0 ---")
datos_sensor[:, 0] = 0
print(f"{datos_sensor}\n")


# 5. Extracción y Modificación de un Bloque Interno
print("--- 5. Modificando un Bloque Interno (x100) ---")
# Seleccionamos el bloque
bloque_central = datos_sensor[2:4, 2:4]
print(f"Bloque central original:\n{bloque_central}")

# Modificamos el bloque y lo reasignamos
datos_sensor[2:4, 2:4] = bloque_central * 100
print("\nMatriz final con el bloque modificado:")
print(datos_sensor)


--- 1. Matriz Original de Datos del Sensor ---
[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]
 [12 13 14 15 16 17]
 [18 19 20 21 22 23]
 [24 25 26 27 28 29]
 [30 31 32 33 34 35]]

--- 2. Selección de Filas Pares ---
[[ 0  1  2  3  4  5]
 [12 13 14 15 16 17]
 [24 25 26 27 28 29]]

--- 3. Modificando la Última Fila a 99 ---
[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]
 [12 13 14 15 16 17]
 [18 19 20 21 22 23]
 [24 25 26 27 28 29]
 [99 99 99 99 99 99]]

--- 4. Modificando la Primera Columna a 0 ---
[[ 0  1  2  3  4  5]
 [ 0  7  8  9 10 11]
 [ 0 13 14 15 16 17]
 [ 0 19 20 21 22 23]
 [ 0 25 26 27 28 29]
 [ 0 99 99 99 99 99]]

--- 5. Modificando un Bloque Interno (x100) ---
Bloque central original:
[[14 15]
 [20 21]]

Matriz final con el bloque modificado:
[[   0    1    2    3    4    5]
 [   0    7    8    9   10   11]
 [   0   13 1400 1500   16   17]
 [   0   19 2000 2100   22   23]
 [   0   25   26   27   28   29]
 [   0   99   99   99   99   99]]


### **Ejercicio 13: Métodos, Atributos y Slicing Combinado en NumPy**

**Instrucciones:**

1.  **Creación y Remodelación (`.reshape`)**:
    * Crea un array 1D con 24 números enteros, del 0 al 23, usando `np.arange()`.
    * Inmediatamente después, utiliza el método `.reshape()` para transformar el array en una matriz de 4x6 (4 filas, 6 columnas). Llama a esta matriz `matriz_principal`.
    * Imprime la `matriz_principal`.

2.  **Atributos y Transposición (`.T`)**:
    * Imprime la forma (`.shape`) de la `matriz_principal`.
    * Obtén y muestra la **transpuesta** de la matriz utilizando el atributo `.T`. La transpuesta intercambia las filas por las columnas.

3.  **Slicing de Bloques**:
    * De la `matriz_principal` original, extrae y muestra un bloque (sub-matriz) de 2x2 que se encuentra en la esquina superior derecha.

4.  **Slicing con Pasos (Step)**:
    * Utiliza slicing con un paso de 2 para crear una nueva matriz llamada `matriz_alternada` que contenga solo las filas con índice par (0, 2) y las columnas con índice impar (1, 3, 5) de la `matriz_principal`.
    * Imprime la `matriz_alternada`.

5.  **Modificación Vía Slicing**:
    * Toma la `matriz_alternada` que acabas de crear.
    * Selecciona su segunda fila completa (índice 1) y actualiza sus valores para que sean `[99, 98, 97]`.
    * Imprime la `matriz_alternada` modificada para ver el resultado.

In [22]:
import numpy as np

# 1. Creación y Remodelación (.reshape)
print("--- 1. Matriz Principal (4x6) ---")
matriz_principal = np.arange(24).reshape(4, 6)
print(f"{matriz_principal}\n")


# 2. Atributos y Transposición (.T)
print("--- 2. Atributos y Matriz Transpuesta ---")
print(f"Forma de la matriz principal: {matriz_principal.shape}")
matriz_transpuesta = matriz_principal.T
print("Matriz transpuesta (6x4):")
print(f"{matriz_transpuesta}\n")


# 3. Slicing de Bloques
print("--- 3. Extrayendo la Esquina Superior Derecha (2x2) ---")
# Filas 0 a 1, Columnas 4 a 5
esquina_superior_derecha = matriz_principal[0:2, 4:6]
print(f"{esquina_superior_derecha}\n")


# 4. Slicing con Pasos (Step)
print("--- 4. Creando una Matriz con Filas Pares y Columnas Impares ---")
# Filas ::2 (0, 2, 4...), Columnas 1::2 (1, 3, 5...)
matriz_alternada = matriz_principal[::2, 1::2]
print(f"{matriz_alternada}\n")


# 5. Modificación Vía Slicing
print("--- 5. Modificando una Fila de la Matriz Alternada ---")
matriz_alternada[1, :] = [99, 98, 97]
print("Matriz alternada después de la modificación:")
print(matriz_alternada)

--- 1. Matriz Principal (4x6) ---
[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]
 [12 13 14 15 16 17]
 [18 19 20 21 22 23]]

--- 2. Atributos y Matriz Transpuesta ---
Forma de la matriz principal: (4, 6)
Matriz transpuesta (6x4):
[[ 0  6 12 18]
 [ 1  7 13 19]
 [ 2  8 14 20]
 [ 3  9 15 21]
 [ 4 10 16 22]
 [ 5 11 17 23]]

--- 3. Extrayendo la Esquina Superior Derecha (2x2) ---
[[ 4  5]
 [10 11]]

--- 4. Creando una Matriz con Filas Pares y Columnas Impares ---
[[ 1  3  5]
 [13 15 17]]

--- 5. Modificando una Fila de la Matriz Alternada ---
Matriz alternada después de la modificación:
[[ 1  3  5]
 [99 98 97]]
