# Capítulo 1.

### 1.1 Introducción al Intérprete de Python

En este primer capítulo, exploraremos las funcionalidades esenciales de Python, desde las operaciones aritméticas más simples hasta la manipulación de vectores y matrices con la ayuda de la biblioteca NumPy, sentando así las bases para que el lector pueda aplicar estos conocimientos en sus propios análisis económicos. Este libro no pretende ser un manual para programadores, sino más bien, una herramienta para economistas que buscan una manera eficiente y flexible de analizar datos, realizar cálculos, y automatizar tareas repetitivas sin necesidad de una formación exhaustiva en las ciencias computacionales o la informática.

Antes de iniciar, es fundamental entender el **intérprete de Python**, el cual es un programa que lee y ejecuta las instrucciones que escribimos en lenguaje Python, línea por línea. Cuando se instala Python en una computadora, también se instala este intérprete. De manera general, la mayoría de los sistemas operativos (SO) más populares vienen con una instalación de Python, al cual se puede acceder de diferentes maneras, a continuación, se mostrarán las formas básicas de acceder al intérprete en los tres SO’s más populares.


En Windows:




1.   Abrir el menú de búsqueda presionando la tecla “Windows” en el teclado o seleccionando el ícono de inicio en la barra de aplicaciones.
2.   En la barra de búsqueda escribe la palabra "Terminal" o “CMD” y selecciona la aplicación que aparece en los resultados de la búsqueda.
3. En la terminal escribe la palabra “python” o “python3” esto mostrara la ventana del intérprete de “python” donde se pueden escribir comandos directamente

En macOS:


1. Abre el menú de búsqueda presionando las teclas “command + barra espaciadora” y escribe la palabra “terminal”
2. Selecciona la aplicación que aparece en los resultados de la búsqueda.
3. En la terminal escribe la palabra “python” o “python3” esto mostrara la ventana del intérprete de “python” donde se pueden escribir comandos directamente.


En Linux: Abre la aplicación "Terminal" y escribe el comando “python” o “python3” (dependiendo de la configuración). Presiona “Enter”, y se mostrará una indicación como “>>>”, la cual indica que el intérprete está listo para recibir comandos.

Para salir del intérprete de “python” escribe el comando “exit()”, esto cerrará el interpreté de “python” y regresará la sesión de la terminal. Para cerrar la terminal escribe la palabra “exit” y presiona la tecla “enter” en el teclado, esto cerrará la ventana de la terminal.

La interfaz es muy útil para realizar pequeñas porciones de código y entender cómo funcionan las diferentes instrucciones de Python de forma básica.

### 1.2 Conceptos básicos

#### 1.2.1 Declaración y asignación de variables

##### __Asignación de una variable__

En Python, una variable es un nombre que se refiere a un valor. Podemos pensar en una variable como un objeto que almacena un valor. La asignación es el proceso de darle un valor a una variable, y se realiza utilizando el signo igual (=). Por ejemplo, si queremos guardar el valor de la tasa de interés anual (digamos, 0.05) en una variable llamada tasa_interes, escribiríamos en el intérprete:

In [2]:
tasa_interes = 0.05
print(tasa_interes)

0.05


##### __Asignación de variable con un cálculo__

Después de ejecutar esta línea, la variable tasa_interes "almacena" el valor 0.05. Podemos usar esta variable en cálculos posteriores, en el siguiente ejemplo, asignamos valores a otras variables y realizamos una operación (multiplicación) que se asigna a otra variable, finalmente, mostramos el resultado con la función “print”, la cual permite imprimir el contenido de la variable.

El siguiente ejemplo ilustra cómo las variables nos permiten organizar y reutilizar valores de manera eficiente

In [3]:
capital_inicial = 1000
interes_ganado = capital_inicial * tasa_interes

print(interes_ganado)


50.0


##### __Error en la asignación de variables__

Para la declaración y asignación nombres de variables es importante tomar en cuenta las siguientes indicaciones:

1. El nombre de una variable debe comenzar con una letra o guion bajo _ (no puede comenzar con un numero).  

In [ ]:


1capital_inicial = 1000

SyntaxError: invalid decimal literal (277653954.py, line 1)

##### __Error en la asignación de variables__

2. El nombre de las variables solo puede contener letras, números y guion bajo “_”, no puede contener caracteres especiales como “#”, “:”, “(”, etc.

In [ ]:

cap:tal_inicial = 1000

NameError: name 'tal_inicial' is not defined

##### __Capitalización en la asignación de variables__

3. El nombre de una variable se distingue entre mayúsculas y minúsculas

In [5]:
capital_inicial = 1000
Capital_inical = 2000

print(capital_inicial, Capital_inical, sep="\n")

1000
2000


__Error en la asignación de variables__

4. El nombre de una variable no puede usar palabras reservadas de Python como “if”, ”while”, “def”, etc.

In [ ]:

if = "nombre de variable"

SyntaxError: invalid syntax (1717109559.py, line 1)

In [ ]:

while = 1589

SyntaxError: invalid syntax (2773075343.py, line 1)

In [ ]:

def = "La palabra def es una palabra reservada por Python"

SyntaxError: invalid syntax (2834945956.py, line 1)

#### 1.2.2 Tipos de Datos (Enteros, Flotantes, Cadenas de texto)

Python reconoce diferentes tipos de datos, cada uno adecuado para representar distintos tipos de información. Los tipos de datos escalares (representan un único valor) más básicos son:

##### __Enteros, decimales, texto (String), Bool, None__



* Enteros (int): Números enteros, sin parte decimal. Ejemplos: -5, 0, 100.
* Flotantes (float): Números con parte decimal. Ejemplos: -3.14, 0.0, 2.71828.
* Cadenas de texto (str): Secuencias de caracteres utilizadas para representar texto. Se definen entre comillas simples (') o dobles ("). Ejemplos: 'Hola', "Análisis Económico".
* Booleanos (bool): Representan valores de verdad: True (verdadero) o False (falso). Son fundamentales para la lógica condicional y el control de flujo en los programas. Por ejemplo, podríamos tener una variable booleana que indique si una condición económica se cumple o no.
* None (None Type) Representan la ausencia de un valor

Python automáticamente detecta el tipo de dato de una variable al asignarle un valor, para verificar el tipo de dato de una variable podemos usar la función type(); también podemos imprimir varias variables dentro de la función “print” y utilizar el argumento “sep” el cual permite agregar un elemento de separación entre cada una de las variables dentro de la función, en el siguiente ejemplo se usa “\n”, que representa un salto de línea:



In [ ]:
numero_entero = 10
numero_decimal = 3.14
texto = "Python para Economistas"
valor_booleano = True
valor_none = None

print(type(numero_entero), type(numero_decimal), type(texto), type(valor_booleano),
type(valor_none), sep="\n")


<class 'int'>
<class 'float'>
<class 'str'>
<class 'bool'>
<class 'NoneType'>


##### __Listas, tuplas, diccionarios__

Otras estructuras de datos importantes en Python son tipos de datos que pueden contener múltiples elementos, organizándolos de una manera específica, estas estructuras de datos se abordaran más adelante de forma específica, particularmente el caso de las listas, sin embargo, vale la pena que el lector se familiarice con estas estructuras de datos, las más comunes son:


* **Listas (list)**: Colecciones ordenadas y mutables de elementos. Pueden contener elementos de diferentes tipos. Se definen utilizando corchetes []. Ejemplos: [1, 2.5, 'dato'], [10, 20, 30]. Son una forma básica de representar secuencias de datos, como series de tiempo.
* **Tuplas (tuple)**: Similares a las listas, pero son inmutables (no se pueden modificar después de su creación). Se definen utilizando paréntesis (). Ejemplos: (1, 2.5, 'dato'), ('año', 2023). Pueden ser útiles para representar datos que no deberían cambiar, como las coordenadas de un punto fijo.
* **Diccionarios (dict)**: Colecciones de pares clave-valor, donde cada clave es única y se utiliza para acceder a su valor correspondiente. Se definen utilizando llaves 1 {}. Ejemplos: {'nombre': 'Producto A', “precio”: 150.75}. Son muy útiles para representar datos estructurados y realizar búsquedas eficientes.



In [6]:
lista_valores = [1, 2.5, 'dato']
tupla_valores = (1, 2.5, 'dato'), ('año', 2023)
diccionario_valores = {"nombre": "Producto A", "precio": 150.75}

print(type(lista_valores), type(tupla_valores), type(diccionario_valores), sep="\n")

<class 'list'>
<class 'tuple'>
<class 'dict'>


#### 1.2.3 Operaciones Aritméticas y orden de precedencia de operadores

Python puede realizar operaciones aritméticas básicas como suma (+), resta (-), producto(*), división (/), división módulo (%), división entera (//) y potenciación (**).

In [7]:
print("Suma:", 5 + 3)
print("Resta:", 10 - 4)
print("Producto:", 2 * 7)
print("Division:", 15 / 3) #la división siempre produce un número flotante
print("Division entera:", 15 // 3) #la división entera produce un número entero
print("Division modulo:", 10 % 3) #la división módulo produce el residuo
print("Potencia:", 2 ** 4) #el primer número es la base y el segundo es el exponente

Suma: 8
Resta: 6
Producto: 14
Division: 5.0
Division entera: 5
Division modulo: 1
Potencia: 16


Al igual que en matemáticas, Python sigue un orden de precendencia de operadores para determinar en que se realizan las operaciones en una expresión., el orden general es:

1.	Paréntesis () (las operaciones dentro de los paréntesis se evalúan primero).
2.	Potenciación (**).
3.	Multiplicación (*), División (/), Módulo (%), y División entera (//) (se evalúan de izquierda a derecha).
4.	Suma (+) y Resta (-) se evalúan de izquierda a derecha.

Es recomendable hacer uso de paréntesis para asegurar que las operaciones se realicen en el orden deseado y para hacer el código más legible.


#### 1.2.4 Operadores de comparación

Los operadores de comparación se utilizan para comparar valores, estos devuelven un resultado booleano (True, False).  

In [ ]:
print(5 == 5) # Igual a
print(5 != 5) # Distinto de
print(5 < 5) # Menor que
print(5 > 5) # Mayor que
print(5 <= 5) # Menor o igual que
print(5 >= 5) # Mayor o igual que

True
False
False
False
True
True


#### 1.2.5 La función “print” y comentarios en Python

##### __Función print()__

La función `print()` es esencial para mostrar información en la pantalla, como hemos visto en ejemplos anteriores, podemos usarla para ver el resultado de cálculos o el valor de variable; la sintaxis básica de la función `print()` es:
`print(objeto(s))`.

In [ ]:
print("Esto es un ejemplo de la función print()")

Esto es un ejemplo de la función print()


##### __Función print() con separación__


Objeto(s), es el objeto o los objetos que se van a imprimir, los cuales pueden ser cadenas de texto, números, variables, expresiones, etc. La función `print()` puede hacer uso de argumentos como el separador “sep”, esto permite colocar un elemento de separación entre cada objeto., la sintaxis es `print(objeto, objeto, sep=separador)`

- sep=separador: Especifica el separador entre los objetos. Por defecto, es un espacio en blanco, pero pueden ser comas u otros caracteres como un salto de línea “\n”.

In [10]:
print("Esto es una línea", "esto está en la siguiente linea", sep = "\n")
print("Esto es una ejemplo de", "texto separado", "por comas",
      "y un espacio después de la coma", sep=", ")

Esto es una línea
esto está en la siguiente linea
Esto es una ejemplo de, texto separado, por comas, y un espacio después de la coma


##### __Función print() con formato__

La función `print()` también nos permite realizar un formato a los datos de salida como: el número de decimales, los separadores de miles, el tipo de dato (entero, decimal, porcentaje, etc.), la alineación del texto, o incluso el estilo (como agregar ceros a la izquierda). A continuación, mostraremos algunos ejemplos básicos para dar formato a los datos de salida con la función “print”.

In [11]:
pi = 3.14159265
ingreso = 1234567.8910
tasa = 0.075

# formato de decimales
print(f"El valor de PI es aproximadamente {pi:.2f}")
# formato de dinero separador de miles
print(f"Ingreso anual: ${ingreso:,.2f}")
# formato de decimales
print(f"Tasa de interés: {tasa:.2%}") # formato de porcentaje

El valor de PI es aproximadamente 3.14
Ingreso anual: $1,234,567.89
Tasa de interés: 7.50%


Para limitar la visualización de un número decimal a solo dos cifras después del punto, se utiliza el formato :.2f. Si además se desea aplicar formato monetario, es decir, separar los miles con comas y mantener dos decimales, se usa :,.2f. Por otro lado, para mostrar un valor como porcentaje, se emplea el formato :.2%, donde 2 indica el número de decimales a mostrar y el símbolo % representa que el valor será convertido y presentado como porcentaje. Por ejemplo, si la variable tasa contiene el valor 0.12341, al aplicar "{:.2%}" se obtendrá como salida 12.34%.

#### 1.2.6 Comentarios en Python

Una de las partes fundamentales en cualquier lenguaje de programación son los comentarios, los cuales son líneas de texto en el código que Python ignora. Se utilizan para explicar el código y hacerlo más comprensible para los humanos. En Python, existen dos formas de colocar comentarios, la primera se le conoce como comentario de línea, el cual se escribe con el símbolo de numeral (#):

##### __Comentarios de linea__

In [12]:
# Este es un comentario explicando la siguiente línea de código
tasa_crecimiento =  0.02  # Tasa de crecimiento anual (2%)

print(tasa_crecimiento)

0.02


##### __Comentarios multilínea (o docstrings)__

La segunda forma se le conoce como comentarios multilínea (o docstrings), estos se definen utilizando tres comillas dobles (""") o tres comillas simples ('''). Aunque técnicamente son cadenas de texto, cuando se utilizan al principio de un módulo, función, clase o método, se interpretan como docstrings (cadenas de documentación) y se utilizan para documentar el código. También se pueden usar como comentarios multilínea en cualquier otra parte del código

In [14]:

"""
Este es un comentario que ocupa varias líneas.
Puede ser útil para explicar secciones de código más extensas.
"""
'''
También se pueden usar tres comillas simples para comentarios multilínea.
'''

' \nTambién se pueden usar tres comillas simples para comentarios multilínea. \n'

### 1.3 Listas en Python: Representación Básica de Vectores y "Matrices"

Las listas son una de las estructuras de datos más versátiles en Python. Permiten almacenar una colección ordenada de elementos, que pueden ser de diferentes tipos. En el contexto económico, podemos pensar en listas como una forma básica de representar vectores y, anidando listas, podemos simular matrices.

#### 1.3.1 Creación de Listas (Vectores Simples)

Para crear una lista, encerramos los elementos entre corchetes [], separándolos por comas:

In [15]:
tasas_anuales = [0.03, 0.04, 0.035, 0.05] # Lista de tasas de interés anuales
PIB_trimestral = [250.5, 260.2, 275.8, 280.1] # Lista del PIB trimestral
nombres_paises = ['México', 'Canadá', 'Estados Unidos'] # Lista de cadenas de texto

print(tasas_anuales, PIB_trimestral, nombres_paises, sep="\n")

[0.03, 0.04, 0.035, 0.05]
[250.5, 260.2, 275.8, 280.1]
['México', 'Canadá', 'Estados Unidos']


##### __Una lista puede contener elementos de diferentes tipos__

In [ ]:
datos_mixtos = [1, "inflación", 0.025, True]
print(datos_mixtos)

[1, 'inflación', 0.025, True]


#### 1.3.2 Acceso a Elementos de una Lista (Indexación)

Cada elemento en una lista tiene una posición, llamada índice. En Python (y en muchos otros lenguajes de programación), la indexación comienza desde 0. Esto significa que el primer elemento de una lista tiene el índice 0, el segundo tiene el índice 1, y así sucesivamente.

Para acceder a un elemento específico de una lista, utilizamos el nombre de la lista seguido del índice del elemento entre corchetes:

In [16]:
tasas_anuales = [0.03, 0.04, 0.035, 0.05]
primera_tasa = tasas_anuales[0] # Accede al primer elemento (0.03)
segunda_tasa = tasas_anuales[1] # Accede al segundo elemento (0.04)
ultima_tasa = tasas_anuales[3] # Accede al cuarto elemento (0.05)

print(tasas_anuales)
print(primera_tasa)
print(segunda_tasa)
print(ultima_tasa)

[0.03, 0.04, 0.035, 0.05]
0.03
0.04
0.05


##### __Último elemento de lista__

Podemos usar índices negativos para acceder a los elementos desde el final de la lista. El último elemento tiene el índice -1, el penúltimo -2, y así sucesivamente:

In [17]:

ultima_tasa = tasas_anuales[-1] # Accede al último elemento (0.05)
penultima_tasa = tasas_anuales[-2] # Accede al penúltimo elemento (0.035)

print(ultima_tasa)
print(penultima_tasa)

0.05
0.035


#### 1.3.3 Slicing de Listas

El **slicing** permite extraer una porción de una lista, creando una nueva lista que contiene los elementos seleccionados. La sintaxis general para el slicing es `lista[inicio:fin:paso]`

    - inicio: Índice del primer elemento que se incluirá (opcional, por defecto es 0).

    - fin: Índice del primer elemento que no se incluirá (opcional, por defecto es la longitud de la lista).

    - paso: El incremento entre los índices (opcional, por defecto es 1).

In [ ]:

tasas_anuales = [0.03, 0.04, 0.035, 0.05, 0.042]
# Elementos desde el índice 0 hasta el 2
primeras_tres = tasas_anuales[0:3]
del_segundo_en_adelante = tasas_anuales[1:]
# Elementos desde el índice 1 hasta el final
hasta_el_penultimo = tasas_anuales[:-1]
# Elementos desde el inicio hasta el penúltimo con un paso de 2
cada_dos = tasas_anuales[::2]
# Elementos con un paso de 1 del último elemento al primero
invertida = tasas_anuales[::-1]


print(tasas_anuales)
print(primeras_tres)
print(del_segundo_en_adelante)
print(hasta_el_penultimo)
print(cada_dos)
print(invertida)

[0.03, 0.04, 0.035, 0.05, 0.042]
[0.03, 0.04, 0.035]
[0.04, 0.035, 0.05, 0.042]
[0.03, 0.04, 0.035, 0.05]
[0.03, 0.035, 0.042]
[0.042, 0.05, 0.035, 0.04, 0.03]


#### 1.3.4 Operaciones Básicas con Listas (concatenación, repetición)

Las listas de Python soportan algunas operaciones básicas:

##### __Concatenación__

Es posible combinar dos o más listas utilizando el operador “+”:

In [18]:
lista1 = [1, 2, 3]
lista2 = [4, 5, 6]
lista_combinada = lista1 + lista2

print(lista_combinada)

[1, 2, 3, 4, 5, 6]


##### __Repetición__

Es posible repetir los elementos de una lista un cierto número de veces utilizando el operador `*`

In [ ]:
lista_original = ['a', 'b']
lista_repetida = lista_original * 3

print(lista_repetida) # Salida: ['a', 'b', 'a', 'b', 'a', 'b']

['a', 'b', 'a', 'b', 'a', 'b']


#### 1.3.5 Listas de Listas para Representar "Matrices"

Aunque Python no tiene un tipo de dato nativo para matrices, podemos representar matrices utilizando listas. Cada lista interna representa una fila de la matriz. Por ejemplo, una matriz de 2x3 podría representarse de la siguiente forma:

In [ ]:
matriz_ejemplo = [[1, 2, 3], [4, 5, 6]]

print(matriz_ejemplo)

[[1, 2, 3], [4, 5, 6]]


##### __Indexación__

Para acceder a un elemento específico de esta "matriz", primero accedemos a la fila (que es una lista) y luego al elemento dentro de esa fila usando otro índice.

In [ ]:
primer_elemento_primera_fila = matriz_ejemplo[0][0]
segundo_elemento_segunda_fila = matriz_ejemplo[1][1]

print(matriz_ejemplo, primer_elemento_primera_fila, segundo_elemento_segunda_fila, sep = "\n")

[[1, 2, 3], [4, 5, 6]]
1
5


Si bien las listas pueden representar vectores y las listas de listas también son útiles para representar matrices y realizar operaciones básicas, para cálculos vectoriales y matriciales más eficientes y complejos, Python hace uso de la librería “NumPy”, la cual se describe a detalle en las siguientes secciones.

### 1.4 Introducción a NumPy: Arrays para Cálculos Eficientes

NumPy es una biblioteca fundamental en Python para la computación numérica, la cual proporciona soporte para arrays (arreglos) unidimensionales, bidimensionales y multidimensionales, así como una gran colección de funciones matemáticas de alto nivel optimizadas.

#### 1.4.1 ¿Por qué NumPy para el Análisis Numérico en Economía?

En economía, frecuentemente trabajamos con grandes conjuntos de datos numéricos, como series de tiempo, datos de panel, matrices de coeficientes, etc. Realizar operaciones con listas de Python para este tipo de datos puede ser ineficiente en términos de rendimiento y también puede resultar en un código más complejo de escribir y mantener.
NumPy ofrece varias ventajas cruciales para el análisis numérico en economía:
- Eficiencia en el almacenamiento y las operaciones: Los arrays de NumPy están implementados de manera que las operaciones se realizan de forma mucho más rápida que con las listas de Python, especialmente para grandes conjuntos de datos. Esto se debe a la forma en que NumPy almacena los datos en memoria y a las optimizaciones implementadas en sus funciones.
- Sintaxis concisa y poderosa: NumPy proporciona una sintaxis intuitiva para realizar operaciones complejas con arrays, lo que hace que el código sea más legible y fácil de escribir.
- Gran cantidad de funciones matemáticas: NumPy incluye una amplia gama de funciones matemáticas, estadísticas, algebraicas y de manipulación de arrays que son esenciales para el análisis económico

#### 1.4.2 Importación de la Biblioteca NumPy (import numpy as np)

Antes de poder utilizar las funcionalidades de NumPy, necesitamos importar la biblioteca en nuestro código. En algunos casos, la librería
podría no estar instalada, para instalar la librería se usa el comando `!pip install numpy`, el signo de exclamación es para instalar la librería
dentro del Notebook, si se instala desde la terminal el comando sería sin el signo de exclamación `pip install numpy`

In [ ]:
import numpy as np


Una vez que hemos importado NumPy, podemos acceder a sus funciones utilizando el prefijo “np”.

#### 1.4.3 Creación de Arrays en NumPy  

Una de las formas más comunes de crear un array NumPy es a partir de una lista (o lista de listas) de Python. Esto se realiza utilizando la función `np.array()`

In [ ]:
import numpy as np

lista = [1, 2, 3, 4]
array = np.array(lista)

matriz = [[1, 2, 3], [4, 5, 6]]
array_numpy = np.array(lista)
matriz_numpy = np.array(matriz)

print(array_numpy, matriz_numpy, sep="\n")

[1 2 3 4]
[[1 2 3]
 [4 5 6]]


#### 1.4.4 Tensores (array multidimensional)

El término tensor en el contexto de NumPy se refiere a un array que puede tener un número arbitrario de dimensiones. Un vector es un tensor de una dimensión, una matriz es un tensor de dos dimensiones, y podemos tener tensores con más de dos dimensiones. Podemos decir, que un tensor es una generalización de los escalares, vectores y matrices a más dimensiones, la siguiente tabla ilustra esto.
| Objeto   | Dimensión (`ndim`) | Nombre Matemático     |
|----------|---------------------|------------------------|
| Escalar  | 0                   | Tensor de rango 0      |
| Vector   | 1                   | Tensor de rango 1      |
| Matriz   | 2                   | Tensor de rango 2      |
| Array 3D | 3                   | Tensor de rango 3      |

Aunque no profundizaremos en tensores de alta dimensionalidad en este capítulo, es importante saber que NumPy está diseñado para trabajar eficientemente con estructuras de datos de esta naturaleza, lo cual es fundamental en áreas más avanzadas del análisis económico y la econometría. En este sentido, podemos crear un array de más dimensiones, así mismo, los arrays NumPy permiten usar métodos para conocer las dimensiones y estructura de los mismo, en el siguiente ejemplo, utilizamos “ndim” y “shape” para ver la dimensionalidad del array:

In [ ]:
import numpy

array_multidimensional = np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])

print("Array multidimensional:", array_multidimensional)
print("Array multidimensional shape:", array_multidimensional.shape)
print("Array multidimensional dimensiones: ", array_multidimensional.ndim)

Array multidimensional: [[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]
Array multidimensional shape: (2, 2, 2)
Array multidimensional dimensiones:  3


En el ejemplo anterior, ¿por qué el array tiene una forma (2, 2, 2) y es de 3 dimensiones?, si lo vemos de una forma más clara:  
```python
[
  [ [1, 2], [3, 4] ],
  [ [5, 6], [7, 8] ]
]
```
Podemos descomponermos la estructura en niveles:

- Nivel 1: El array tiene 2 elementos externos → [...], por eso el primer valor del shape es 2.
- Nivel 2: Cada uno de esos elementos es una lista de 2 elementos → [[1, 2], [3, 4]], por eso el segundo valor del shape es 2.
- Nivel 3: Cada sublista contiene 2 elementos numéricos → [1, 2], por eso el tercer valor del shape es 2.



#### 1.4.5 Otras formas de crear arrays en NumPy

Además de usar np.array() a partir de listas, NumPy proporciona varias funciones útiles para crear arrays de forma automática, especialmente cuando se necesita inicializar vectores o matrices con ciertos valores por defecto.

- `np.arange(inicio, fin, paso)`: Crea un array con valores dentro del intervalo [inicio, fin), con un incremento de paso. Similar a la función range() de Python, pero devuelve un array NumPy.

In [ ]:
import numpy as np

# Crear un array desde 0 hasta (pero no incluyendo) 10, con paso de 0.5

vector_arange = np.arange(0, 10, 0.5)

print(vector_arange)

[0.  0.5 1.  1.5 2.  2.5 3.  3.5 4.  4.5 5.  5.5 6.  6.5 7.  7.5 8.  8.5
 9.  9.5]


- `np.zeros()`: Crea un array lleno de ceros, útil para inicializar estructuras que luego serán modificadas.

In [ ]:

a = np.zeros(5)
print(a)

b = np.zeros((2, 3))
print(b)

[0. 0. 0. 0. 0.]
[[0. 0. 0.]
 [0. 0. 0.]]


- `np.ones()`: Similar a np.zeros(), pero llena el array con unos:

In [ ]:

c = np.ones(4)
print(c)

d = np.ones((3, 2), dtype=int)
print(d)

[1. 1. 1. 1.]
[[1 1]
 [1 1]
 [1 1]]


- `np.linspace(inicio, fin, num)`: Crea un array con num valores igualmente espaciados dentro del intervalo [inicio, fin].

In [ ]:

vector_linspace = np.linspace(0, 1, 5)

print(vector_linspace)

[0.   0.25 0.5  0.75 1.  ]


- `np.eye()`: Genera una matriz identidad

In [ ]:

f = np.eye(3)

print(f)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


#### 1.4.6 Acceso a elementos de un array NumPy (Indexación)

Al igual que con las listas de Python, podemos acceder a elementos individuales de un vector NumPy utilizando su índice, que comienza en 0. La sintaxis es similar: el nombre del array seguido del índice entre corchetes [].

In [ ]:
import numpy as np

vector_tasas = np.array([0.02, 0.03, 0.025, 0.04])
primera_tasa = vector_tasas[0] # Accede al primer elemento (índice 0)
ultima_tasa = vector_tasas[-1] # Accede al último elemento (índice -1)

matriz_precios = np.array([ [100, 200, 300], [110, 210, 310], [120, 220, 320] ])
precio_central = matriz_precios[1, 1] # Fila 2, columna 2

print("La primera tasa es:", primera_tasa)
print("La última tasa es:", ultima_tasa)
print("El precio central es:", precio_central)

La primera tasa es: 0.02
La última tasa es: 0.04
El precio central es: 210


#### 1.4.7 Slicing de arrays NumPy

El slicing en arrays NumPy funciona de manera muy similar al _slicing_ de listas en Python, permitiéndonos extraer subconjuntos de elementos. La sintaxis general es `vector[inicio:fin:paso]`.

In [ ]:
import numpy as np

vector_precios = np.array([10.5, 11.2, 11.8, 12.1, 12.5, 12.8])
primeros_tres_precios = vector_precios[0:3] # Elementos desde el índice 0 hasta el 2 (sin incluir el 3)
precios_cada_dos = vector_precios[::2] # Elementos con un paso de 2
ultimos_dos_precios = vector_precios[-2:] # Los últimos dos elementos

print("Primeros tres precios:", primeros_tres_precios)
print("Precios cada dos:", precios_cada_dos)
print(f"Los últimos dos precios: {ultimos_dos_precios}")

Primeros tres precios: [10.5 11.2 11.8]
Precios cada dos: [10.5 11.8 12.5]
Los últimos dos precios: [12.5 12.8]


El _slicing_ es una herramienta poderosa para seleccionar rangos específicos de datos en la series económicas o conjuntos de indicadores

#### 1.4.8 Operaciones Elemento a Elemento con arrays NumPy

Una de las grandes ventajas de NumPy es su capacidad para realizar operaciones aritméticas de manera elemento a elemento en arrays. Esto significa que, si aplicamos una operación a un vector, se aplicará individualmente a cada uno de sus elementos.

In [ ]:
import numpy as np

tasas_interes = np.array([0.05, 0.06, 0.04])
factor_inflacion = 1.02 # Multiplicar cada tasa por el factor de inflación
tasas_ajustadas = tasas_interes * factor_inflacion

print(tasas_interes)
print(factor_inflacion)
print(tasas_ajustadas)

[0.05 0.06 0.04]
1.02
[0.051  0.0612 0.0408]


Estas operaciones elemento a elemento son mucho más eficientes y concisas que realizar las mismas operaciones utilizando bucles en listas de Python, lo que es crucial para el análisis de grandes conjuntos de datos económicos.

### 1.5 Indentación en Python  

En Python, la indentación es una parte fundamental de la sintaxis, no es solo como una cuestión de estilo o legibilidad, ya que a diferencia de otros lenguajes que usan llaves “{}” o palabras clave para definir bloques de código, Python utiliza la indentación para delimitar la estructura y el alcance de bloques asociados a funciones, bucles, condicionales y otros contextos. Algunas recomendaciones básicas a tomar en cuenta para la indentacion en Python:  

- Usar 4 espacios por nivel, aunque también se aceptan 8 espacios.  

- Todos los bloques indentados deben tener el mismo nivel de indentación.

- Si la indentación es incorrecta, Python lanzará un error como “IndentationError” o “SyntaxError”.

Aunque aún no hemos explorado funciones, condicionales o bucles (donde la indentación se utiliza de manera constante), es fundamental comprender su importancia desde el principio. La indentación en Python no es opcional, esta define la estructura del código. Para ilustrar este concepto, veamos algunos ejemplos básicos:

In [ ]:

if True: # condición en python
    print("¡Hola!")  # Código indentado

¡Hola!


In [ ]:

if True: # condición en python
print("¡Hola!")  # Error: Falta indentación

IndentationError: expected an indented block after 'if' statement on line 1 (1310390480.py, line 2)

En el ejemplo anterior podemos observar que, en el primer bloque, la línea print("¡Hola!") está indentada con 4 espacios después del “if”. Esta indentación le indica a Python que esta instrucción pertenece al bloque de código que debe ejecutarse cuando la condición es verdadera. En el segundo bloque, la instrucción “print” no tiene indentación, lo que provocará un error de tipo “IndentationError”. Python requiere que todo el código dentro de un bloque (como el cuerpo de un “if”) esté indentado para poder determinar qué instrucciones pertenecen a ese bloque.

En los siguientes capítulos veremos múltiples ejemplos del uso de la indetación, por el momenot, es curcial recordar los puntes claves antes mencionados.